chore(deps): loopback version update
sourcefuse/loopback4-notifications pull request #119
Opened 2023-03-10 07:48 UTC by gautam23-sf

loopback version update

GH-118

## Description

loopback version update

Fixes #118 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-10 08:31 UTC, Surbhi-sharma1 approved these changes

2023-03-10 12:34 UTC, yeshamavani requested changes

2023-03-10 12:34 UTC, yeshamavani commented on package.json
>      "tslib": "^2.0.0"
add this as well https://github.com/sourcefuse/loopback4-notifications/pull/95

2023-03-13 10:08 UTC, yeshamavani approved these changes

2023-03-13 10:09 UTC, merged

2023-03-14 08:28 UTC, sfdevops commented
:tada: This PR is included in version 5.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-notifications/v/5.2.0)
- [GitHub release](https://github.com/sourcefuse/loopback4-notifications/releases/tag/v5.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: