feat: Socket.io implementation in extension
sourcefuse/loopback4-notifications pull request #3
Opened 2020-09-17 21:39 UTC by mayank-SFIN571

This PR adds implementation for socket.io as a means to send real time messages from server to clients.

Test cases are pending for this.

2020-09-21 17:03 UTC, samarpanB requested changes

2020-09-21 17:03 UTC, samarpanB commented on src/providers/notification.provider.ts
> +    } else if (data.type === MessageType.SocketIO && this.socketProvider) {
socket io is not a new message type. Mesage type will remain push. socket io is just a new push provider.

2020-09-21 17:29 UTC, samarpan-b reviewed
Add docs to readme with usage details

2020-09-21 17:29 UTC, samarpan-b commented on src/types.ts
> +  SocketIO,
remove tthis

2020-09-23 19:44 UTC, samarpan-b requested changes

2020-09-23 19:44 UTC, samarpan-b commented on README.md
> +There are some additional configurations needed in order to allow Pubnub connection. You need to add them as below. Make sure these are added before the provider binding.
why pubnub ?

2020-09-23 19:44 UTC, samarpan-b commented on package.json
> +    "@types/socket.io-client": "^1.4.33",
add to dev deps

2020-09-23 19:57 UTC, samarpan-b approved these changes

2020-09-23 19:57 UTC, merged